/**
 * CSV field encoding — ONE author for every CSV this app emits.
 *
 * Extracted from `src/lib/export.ts` when a second builder (the tax-year export)
 * needed the same rule. Two copies of a quoting routine is how one export ends up
 * neutralizing a formula and the other doesn't, and the export that forgets is the
 * one that hands a spreadsheet a live `=` cell built from a stranger's descriptor.
 *
 * Pure: string in, string out.
 */

/**
 * RFC-4180 quoting + spreadsheet-formula-injection neutralization: a field
 * beginning with `=`, `+`, `-`, `@`, a tab or a CR gets a leading apostrophe so
 * Excel/Sheets treats it as text and never as a formula (Phase-4 critic P2-1).
 *
 * Note the `-` case is why every numeric column must be written by the CALLER as an
 * already-formatted string that this function does not touch — see `csvAmount`.
 */
export function csvField(value: string): string {
  const neutralized = /^[=+\-@\t\r]/.test(value) ? `'${value}` : value;
  return /[",\n\r]/.test(neutralized) ? `"${neutralized.replace(/"/g, '""')}"` : neutralized;
}

/**
 * Integer cents → the plain decimal string every CSV in this app prints. Deliberately
 * NOT passed through `csvField`: a negative amount starts with `-`, and neutralizing it
 * would emit `'-42.10`, which lands in the spreadsheet as text and silently drops out
 * of the reader's own SUM. Amounts are generated by us, never by a descriptor, so there
 * is nothing to neutralize.
 */
export function csvAmount(amountCents: number): string {
  return (amountCents / 100).toFixed(2);
}

/** Join encoded fields into one CSV record. */
export function csvRow(fields: readonly string[]): string {
  return fields.join(',');
}

/** CRLF line endings + a trailing newline, per RFC 4180 and the existing exports. */
export function csvDocument(rows: readonly string[]): string {
  return rows.join('\r\n') + '\r\n';
}
