// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // Canonical schema is SQLite (local dev + tests, zero credentials). For a
  // Postgres deploy, scripts/gen-pg-schema.mjs derives a postgresql schema and
  // scripts/vercel-build.sh points generate/db push at it when DATABASE_URL is
  // set (see vercel.json). DECISIONS #35 / #635.
  schema: process.env["PRISMA_SCHEMA"] ?? "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
